[package]
name = "il2cpp-diff"
description = "Build comparison models for IL2CPP Explorer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
il2cpp-core = { path = "../il2cpp-core" }
il2cpp-disasm = { path = "../il2cpp-disasm" }
serde.workspace = true
